[package]
name = "rsdarksky"
version = "0.1.0"
authors = ["goolord <zacharyachurchill@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
serde = "1.0.82"
serde_json = "1.0.34"
structopt = "0.3.21"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
